<form action ="" method="POST">
        <label for="nit">Capturar El NIT</label>
        <input type="number" name="nit" id="nit" placeholder ="Captura el NIT">
        <label for="nombre">Nombre </label>
        <input type="text" name="nombre" id="nombre" placeholder =" Nombre completo">
        <label for="telefono">Telefono</label>
        <input type="number" name="telefono" id="telefono" placeholder ="Numero Telefonico">
        <label for="direccion">Direccion</label>
        <input type="text" name="direccion" id="direccion" placeholder ="Direccion completa">

        <input type ="submit" value = "Guardar Cliente" class = "btn_save">

      </form>
